version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: managestudent-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourPassword123!"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    restart: unless-stopped

  api:
    build: 
      context: ./API
      dockerfile: Dockerfile
    container_name: managestudent-api
    depends_on:
      - db
    ports:
      - "5050:8080"
    environment:
      - DatabaseProvider=SqlServer
      - ConnectionStrings__DefaultConnection=Server=db;Database=ManageStudentDb;User Id=sa;Password=YourPassword123!;TrustServerCertificate=True
      # Khai báo cấu hình JWT tuỳ chỉnh nếu cần, nếu không nó sẽ lấy từ appsettings.json
    volumes:
      - api-avatars:/app/wwwroot/avatars
      - api-uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: managestudent-frontend
    depends_on:
      - api
    ports:
      - "5173:80"
    restart: unless-stopped

volumes:
  sqldata:
  api-avatars:
  api-uploads:
